### PR TITLE
home: publications secion is right above impact section

### PR DESCRIPTION
**Pull request by maxwofford**
Don't merge yet; waiting for response on #114 before adding to this.

### CODE REVIEW

**Comment by zachlatta** [comment]
Responded to #114!

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
screenshot 2015-08-18 at 4 15 04 pm

Ready for merge @zachlatta

**Comment by MaxWofford** [comment]
This closes #114

**Comment by zachlatta** [comment]
Can we get the logos from each of the publications on there?

On Tue, Aug 18, 2015 at 5:02 PM, Max Wofford <notifications@github.com>
wrote:

> Assigned #136 <https://github.com/hackedu/website/pull/136> to @zachlatta
> <https://github.com/zachlatta>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/pull/136#event-385961669>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
@zachlatta I don't have access to image editing software while in LA, and cannot make these logos black-and-white.

**Comment by zachlatta** [comment]
I can take care of that. I'll get back to you with them.

On Sun, Aug 23, 2015 at 9:13 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> I don't have access to image
> editing software while in LA, and cannot make these logos black-and-white.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/pull/136#issuecomment-134025329>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Alright, just added fda2120, which adds the publication logos themselves. I decided to hold off on adding USA TODAY because we need to get written consent from them to use their logo. Instead, I added an article about us on Nationswell.

Here's a screenshot:

screencapture-localhost-3000-1440603812830

**Comment by MaxWofford** [comment]
@zachlatta Mind if I resize the images?

**Comment by zachlatta** [comment]
I actually think the image size is probably fine, especially if we want the site to look good on retina screens.

**Comment by zachlatta** [comment]
Just mad EdSurge's logo about half as large.

**Comment by MaxWofford** [comment]
@zachlatta The California Sunday Magazine is what I'm worried about. It is 4-5x the height of NationSwell

**Comment by zachlatta** [comment]
Ah, yeah. My concern there is that it'd look a little odd with such a small logo.

tmp

**Comment by MaxWofford** [comment]
We could buy their [old logo](http://www.trademarkia.com/california-sunday-85951884.html)

**Comment by MaxWofford** [comment]
@zachlatta Was the `As seen in...` line removed on purpose?

If so, feel free to merge whenever.

**Comment by zachlatta** [comment]
Yup! It felt kind of cheesy, though I'm open to adding it if you think otherwise.

Going to go ahead and merge.

**Pull request merged**
