### PR TITLE
Link to kiwiirc instead of freenode webchat

### PR DESCRIPTION
**Pull request by ZucchiniZe**
from hackedu/hackedu#284

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you make sure to wrap the line at 80 characters, per @houndci's comment?

**Comment by ZucchiniZe** [comment]
How would you do that? I haven't touched haml in a long time.

**Comment by MaxWofford** [comment]
@ZucchiniZe You can do this by indenting 2 spaces.

**Comment by MaxWofford** [comment]
@zachlatta I can't get to this very quickly. Would you mind checking it out?

**Comment by zachlatta** [comment]
This change was made in 28a2d2b38e4f3edabdd45f8d4b28fa0ccb2f0517. Thanks @ZucchiniZe!

**Pull request closed without merging**
