### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by paked** [comment]
@MaxWofford please update to master

**Comment by zachlatta** [comment]
Looks good to me. Is there an issue with it @paked?

**Comment by paked** [comment]
@zachlatta not anymore :)

**Comment by paked** [comment]
@zachlatta @MaxWofford I don't seem to be able to merge this PR? Could you verify I have write access?

**Comment by zachlatta** [comment]
Ah, sorry about that! I just gave you write access.

**Comment by paked** [comment]
:heart:

**Comment by zachlatta** [comment]
:heart:

On Thu, Dec 31, 2015 at 2:17 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> [image: :heart:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/pull/186#issuecomment-168254830>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request merged**
